import Head from "next/head";
import Index from "../Components/Index";
import Header from "../Components/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="with=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <Index></Index>
    </>
  );
}
